tingcraft/albums/urls.py
from django.conf.urls import patterns, include, url

from .views import AlbumListView, AlbumCreateView, AlbumMediaFramesView


urlpatterns = patterns('',

    url(r'^$', AlbumListView.as_view(), name='list'),
    url(r'^create/$', AlbumCreateView.as_view(), name='create'),
    url(r'^(?P<slug>[-_\w]+)/$', AlbumMediaFramesView.as_view(), name='mediaframes'),

)

tingcraft/blogs/urls.py
from django.conf.urls import patterns, include, url

from .views import BlogListView, BlogCreateView, BlogDetailView


urlpatterns = patterns('',

    url(r'^$', BlogListView.as_view(), name='list'),
    url(r'^create/$', BlogCreateView.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/', BlogDetailView.as_view(), name='detail'),

)

tingcraft/tingcraft/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

from .views import HomeView, UserHomeView
from blogs.views import BlogDetailView

admin.autodiscover()

urlpatterns = patterns('',

    url(r'^$', HomeView.as_view(), name='home'),

    url(r'^api/', include('core.api', namespace='api')),
    url(r'^rest/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^ckeditor/', include('ckeditor.urls')),

    url(r'^accounts/', include('users.urls')),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^(?P<username>[-_\w]+)/$', UserHomeView.as_view(), name='user_home'),
    url(r'^(?P<username>[-_\w]+)/microblog/', include('microblogs.urls', namespace='microblog')),
    url(r'^(?P<username>[-_\w]+)/blog/', include('blogs.urls', namespace='blog')),
    url(r'^(?P<username>[-_\w]+)/noteboard/', include('noteboards.urls', namespace='noteboard')),
    url(r'^(?P<username>[-_\w]+)/album/', include('albums.urls', namespace='album')),
    url(r'^(?P<username>[-_\w]+)/mediaframe/', include('mediaframes.urls', namespace='mediaframe')),
    url(r'^(?P<username>[-_\w]+)/experience/', include('experience.urls', namespace='exp')),

)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^assets/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }),
    )

"""
reserved_word is used to validate username to avoid conflict with existing url patterns
"""
import re

url_splitor = re.compile(r'/|\$|\^|\\b')


def get_reserved_words(url_list):
    reserved_words = []
    for item in url_list:
        url_components = url_splitor.split(item.regex.pattern)
        if len(url_components) > 1:
            reserved_words.append(url_components[1])
    reserved_words = list(set(reserved_words))
    print reserved_words
    return reserved_words

reserved_words = get_reserved_words(urlpatterns)

tingcraft/albums/models.py
from django.db import models
from django.db.models import Q
from django.core.urlresolvers import reverse
from django.conf import settings
from model_utils.models import TimeStampedModel
from slugify import slugify

from mediaframes.models import MediaFrame


class Album(TimeStampedModel):

    owner = models.ForeignKey('users.TingUser')
    name = models.CharField(max_length=30)
    slug = models.SlugField()
    cover = models.ForeignKey('mediaframes.MediaFrame', null=True, blank=True, related_name='cover')
    description = models.CharField(max_length=255, blank=True)

    is_public = models.BooleanField(default=True)

    rank = models.FloatField(default=100.0, blank=True)

    class Meta:
        unique_together = (('owner', 'slug'), )

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Album, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('album:mediaframes', kwargs={'username': self.owner.username, 'slug': self.slug})

    def get_media_frames(self, max_id, size=settings.PAGE_SIZE['MEDIAFRAME']):
        criteria = Q(album=self)
        if max_id:
            criteria = criteria & Q(pk__lt=max_id)
        return MediaFrame.objects.filter(criteria).order_by('-rating', '-created')[:size]

    def get_album_thumb_frames(self):
        mediaframes = MediaFrame.objects.filter(album=self).order_by('-rating', '-created')[:4]
        frame_list = list(mediaframes)
        while len(frame_list) < 4:
            frame_list.append(None)
        return frame_list

tingcraft/albums/forms.py
from django import forms

from .models import Album


class AlbumCreateForm(forms.ModelForm):

    description = forms.CharField(max_length=255, widget=forms.Textarea)

    class Meta:
        model = Album
        fields = ('name', 'description', 'is_public')

    def __init__(self, *args, **kwargs):
        self.owner = kwargs['initial']['owner']
        super(AlbumCreateForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        album = super(AlbumCreateForm, self).save(commit=False)
        if commit:
            album.owner = self.owner
            album.save()
        return album

tingcraft/albums/views.py
from braces.views import LoginRequiredMixin
from django.conf import settings
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView, TemplateView

from .models import Album
from .forms import AlbumCreateForm
from users.models import TingUser
from mediaframes.models import MediaFrame
from core.mixins import OwnerContextMixin, OwnerRequiredMixin
from core.pagination import AlbumPaginationMixin, MediaFramePaginationMixin


class AlbumListView(AlbumPaginationMixin, OwnerContextMixin, ListView):

    model = Album
    context_object_name = 'albums'
    template_name = 'albums/list.html'

    def get_queryset(self):
        self.owner = get_object_or_404(TingUser, username=self.owner_username)
        queryset = self.owner.get_albums(max_id=self.max_id)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(AlbumListView, self).get_context_data(**kwargs)
        context['owner'] = self.owner
        context['private_albums'] = self.owner.get_albums(max_id=self.max_id, public=False)
        context['popular_frames'] = MediaFrame.objects.filter(owner=self.owner, album__is_public=True)\
                                    .order_by('-view_count')[:settings.PAGE_SIZE['POPULAR_SIDEBAR']]
        return context


class AlbumCreateView(LoginRequiredMixin, OwnerContextMixin, OwnerRequiredMixin, CreateView):

    model = Album
    form_class = AlbumCreateForm
    template_name = 'albums/create.html'

    def get_initial(self):
        self.initial['owner'] = self.request.user
        return super(AlbumCreateView, self).get_initial()

    def get_login_url(self):
        return reverse('login')

    def get_sucessful_url(self):
        return reverse('album:list', kwargs={'username': self.request.user})


class AlbumMediaFramesView(MediaFramePaginationMixin, OwnerContextMixin, ListView):

    model = MediaFrame
    context_object_name = 'mediaframes'
    template_name = 'mediaframes/list.html'

    def get_queryset(self):
        slug = self.kwargs['slug']
        self.owner = get_object_or_404(TingUser, username=self.owner_username)
        self.album = get_object_or_404(Album, owner=self.owner, slug=slug)
        queryset = self.album.get_media_frames(max_id=self.max_id)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(AlbumMediaFramesView, self).get_context_data(**kwargs)
        context['owner'] = self.owner
        context['album'] = self.album
        return context

tingcraft/templates/albums/album.html
{% load thumbnail %}
{% load i18n %}
{% load staticfiles %}

<div class="album-container white">
    <a href="{% url 'album:mediaframes' owner_username album.slug %}">
        <p class="text-center">{{ album.name }}</p>
        <div>
            {% if album.cover %}
                {% if album.cover.content_type == 'I' %}
                    {% thumbnail album.cover.image_item.image ALBUM_COVER_CROPPED crop='center' as im %}
                        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"/>
                    {% endthumbnail %}
                {% else %}
                    <img src="{% static 'img/video-default.jpg' %}" width="{{ ALBUM_COVER_WIDTH }}" height="{{ ALBUM_COVER_HEIGHT }}"/>
                {% endif %}
            {% else %}
                <img src="{% static 'img/image-default.jpg' %}" width="{{ ALBUM_COVER_WIDTH }}" height="{{ ALBUM_COVER_HEIGHT }}"/>
            {% endif %}
        </div>
        <div class="album-thumb-div">
            {% for thumb in album.get_album_thumb_frames %}
                {% if thumb %}
                    {% if thumb.content_type == 'I' %}
                        {% thumbnail thumb.image_item.image FRAME_THUMB_CROPPED crop='center' as im %}
                            <span class="thumb-span"><img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"/></span>
                        {% endthumbnail %}
                    {% else %}
                        <span class="thumb-span"><img src="{% static 'img/video-thumb-default.jpg' %}" width="{{ FRAME_THUMB_WIDTH }}" height="{{ FRAME_THUMB_WIDTH }}"/></span>
                    {% endif %}
                {% else %}
                    <span class="thumb-span"><img src="{% static 'img/image-thumb-default.jpg' %}" width="{{ FRAME_THUMB_WIDTH }}" height="{{ FRAME_THUMB_WIDTH }}"/></span>
                {% endif %}
            {% endfor %}
        </div>
    </a>
</div>

tingcraft/templates/albums/create.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load i18n %}

{% block navigation %}
    {% include 'navigation.html' %}
{% endblock %}

{% block content %}
    <form method="post" action="{% url 'album:create' owner_username %}" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            <tr>
                <td>{{ form.name.label_tag }}</td>
                <td>{{ form.name }}</td>
            </tr>
            <tr>
                <td>{{ form.is_public.label_tag }}</td>
                <td>{{ form.is_public }}</td>
            </tr>
        </table>

        {% load wysiwyg %}
        {% wysiwyg_setup %}
            <textarea id="id-description" name="description"></textarea>
        {% wysiwyg_editor "id-description" %}

        <input type="submit" value="Create Album" />
    </form>
{% endblock %}

tingcraft/templates/albums/list.html
{% extends 'user_page_base.html' %}
{% load thumbnail %}
{% load i18n %}
{% load users_tags %}

{% block content %}
    {% if user.is_authenticated and user.username == owner_username %}
        <div>
            <a href="{% url 'album:create' owner_username %}">{% trans 'Create Album' %}</a>
        </div>
    {% endif %}
    <div class="album-list-container left">
        {% for album in albums %}
            {% include 'albums/album.html' %}
        {% endfor %}
        <br>
        {% if user.is_authenticated and user.username == owner_username %}
            <h4> {% trans 'Private Albums:' %}</h4>
            {% for album in private_albums %}
                {% include 'albums/album.html' %}
            {% endfor %}
        {% endif %}
    </div>
    <div class="album-sidebar-container right text-center">
        <p>{% trans 'Popular' %}</p>
        <hr>
        {% for frame in popular_frames %}
            {% thumbnail frame.image_item.image POPULAR_SIDEBAR as im %}
            <a href="{% url 'mediaframe:detail' owner_username frame.pk %}">
                <img class="popular-sidebar" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"/>
            </a>
            {% endthumbnail %}
        {% endfor %}
    </div>
    <br class="clear-both"/>
{% endblock %}