tingcraft/blogs/urls.py
from django.conf.urls import patterns, include, url

from .views import BlogListView, BlogCreateView, BlogDetailView


urlpatterns = patterns('',

    url(r'^$', BlogListView.as_view(), name='list'),
    url(r'^create/$', BlogCreateView.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/', BlogDetailView.as_view(), name='detail'),

)

tingcraft/mediaframes/urls.py
from django.conf.urls import patterns, include, url

from .views import MediaFrameCreateView, MediaFrameDetailView, VideoFrameCreateView, MediaFrameDeleteView


urlpatterns = patterns('',

    url(r'^create/$', MediaFrameCreateView.as_view(), name='create'),
    url(r'^create-video/$', VideoFrameCreateView.as_view(), name='video_create'),
    url(r'^(?P<pk>[0-9]+)/$', MediaFrameDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/delete/$', MediaFrameDeleteView.as_view(), name='delete'),

)

tingcraft/tingcraft/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

from .views import HomeView, UserHomeView
from blogs.views import BlogDetailView

admin.autodiscover()

urlpatterns = patterns('',

    url(r'^$', HomeView.as_view(), name='home'),

    url(r'^api/', include('core.api', namespace='api')),
    url(r'^rest/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^ckeditor/', include('ckeditor.urls')),

    url(r'^accounts/', include('users.urls')),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^(?P<username>[-_\w]+)/$', UserHomeView.as_view(), name='user_home'),
    url(r'^(?P<username>[-_\w]+)/microblog/', include('microblogs.urls', namespace='microblog')),
    url(r'^(?P<username>[-_\w]+)/blog/', include('blogs.urls', namespace='blog')),
    url(r'^(?P<username>[-_\w]+)/noteboard/', include('noteboards.urls', namespace='noteboard')),
    url(r'^(?P<username>[-_\w]+)/album/', include('albums.urls', namespace='album')),
    url(r'^(?P<username>[-_\w]+)/mediaframe/', include('mediaframes.urls', namespace='mediaframe')),
    url(r'^(?P<username>[-_\w]+)/experience/', include('experience.urls', namespace='exp')),

)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^assets/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }),
    )

"""
reserved_word is used to validate username to avoid conflict with existing url patterns
"""
import re

url_splitor = re.compile(r'/|\$|\^|\\b')


def get_reserved_words(url_list):
    reserved_words = []
    for item in url_list:
        url_components = url_splitor.split(item.regex.pattern)
        if len(url_components) > 1:
            reserved_words.append(url_components[1])
    reserved_words = list(set(reserved_words))
    print reserved_words
    return reserved_words

reserved_words = get_reserved_words(urlpatterns)

tingcraft/mediaframes/models.py
from django.db import models
from django.core.urlresolvers import reverse
from model_utils.models import TimeStampedModel

from core.utils import gen_float_decimal


class MediaFrame(TimeStampedModel):
    """
        Photo/Video Frame
    """

    TYPE_IMAGE = 'I'
    TYPE_VIDEO = 'V'

    album = models.ForeignKey('albums.Album')
    owner = models.ForeignKey('users.TingUser')
    description = models.CharField(max_length=500, default='', blank=True)
    """
        Simple solution is more straightforward than GenericForeignKey
        since we have only two types
    """
    content_type = models.CharField(max_length=1)
    image_item = models.ForeignKey('mediabox.MediaImage', null=True, blank=True)
    video_item = models.ForeignKey('mediabox.MediaVideo', null=True, blank=True)

    view_count = models.FloatField(default=gen_float_decimal, blank=True)
    rating = models.FloatField(default=5.0, blank=True)
    rate_count = models.IntegerField(default=0, blank=True)

    def __unicode__(self):
        return self.description

    def get_absolute_url(self):
        return reverse('album:list', kwargs={'username': self.owner.username})

    def get_album_thumb_image_url(self):
        return self.image_item


class FrameComment(TimeStampedModel):

    owner = models.ForeignKey('users.TingUser')
    media_frame = models.ForeignKey('mediaframes.MediaFrame')
    content = models.CharField(max_length=180)
    parent_comment = models.ForeignKey('self', null=True, blank=True, on_delete=models.SET_NULL)

tingcraft/mediaframes/forms.py
from django import forms
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

from .models import MediaFrame
from albums.models import Album
from mediabox.models import MediaImage, MediaVideo


class MediaFrameCreateForm(forms.ModelForm):

    description = forms.CharField(max_length=255, widget=forms.Textarea, required=False)
    image = forms.ImageField(required=False)
    video_code = forms.CharField(max_length=255, widget=forms.Textarea, required=False)
    album = forms.ModelChoiceField(queryset=None, empty_label=None)

    class Meta:
        model = MediaFrame
        fields = ('description', 'image', 'video_code', 'album')

    def __init__(self, *args, **kwargs):
        self.owner = kwargs['initial']['owner']
        super(MediaFrameCreateForm, self).__init__(*args, **kwargs)
        self.album = Album.objects.filter(owner=self.owner).order_by('-created')
        self.fields['album'].queryset = self.album
        if len(self.album) > 0:
            self.fields['album'].initial = self.album[0]

    def clean(self):
        image = self.cleaned_data['image']
        video_code = self.cleaned_data['video_code']
        if not image and not video_code:
            raise forms.ValidationError(_('Please choose a valid image file'))
        return self.cleaned_data

    def save(self, commit=True):
        media_frame = super(MediaFrameCreateForm, self).save(commit=False)
        if commit:
            image = self.cleaned_data['image']
            video_code = self.cleaned_data['video_code']
            if image:
                image_item = MediaImage(image=image, owner=self.owner)
                image_item.save()
                media_frame.content_type = 'I'
                media_frame.image_item = image_item
            elif video_code:
                video_item = MediaVideo(video_code=video_code, owner=self.owner)
                video_item.save()
                media_frame.content_type = 'V'
                media_frame.video_item = video_item
            else:
                raise
            media_frame.owner = self.owner
            media_frame.save()
        return media_frame


class VideoFrameCreateForm(forms.ModelForm):

    description = forms.CharField(max_length=255, widget=forms.Textarea, required=False)
    video = forms.FileField(required=False)
    video_code = forms.CharField(max_length=255, widget=forms.Textarea, required=False)
    album = forms.ModelChoiceField(queryset=None, empty_label=None)

    class Meta:
        model = MediaFrame
        fields = ('description', 'video', 'video_code', 'album')

    def __init__(self, *args, **kwargs):
        self.owner = kwargs['initial']['owner']
        super(VideoFrameCreateForm, self).__init__(*args, **kwargs)
        self.album = Album.objects.filter(owner=self.owner).order_by('-created')
        self.fields['album'].queryset = self.album
        if len(self.album) > 0:
            self.fields['album'].initial = self.album[0]

    def clean_video(self):
        video = self.cleaned_data['video']
        if not video:
            return None
        content_type = video.content_type
        if content_type not in settings.UPLOAD_VIDEO_TYPES:
            raise forms.ValidationError(_('Video file type is not supported'))
        return video

    def clean(self):
        video = self.cleaned_data.get('video', None)
        video_code = self.cleaned_data['video_code']
        if not video and not video_code:
            raise forms.ValidationError(_('Please choose a valid video file or enter a video code'))
        return self.cleaned_data

    def save(self, commit=True):
        media_frame = super(VideoFrameCreateForm, self).save(commit=False)
        if commit:
            video = self.cleaned_data['video']
            video_code = self.cleaned_data['video_code']
            media_frame.content_type = 'V'
            if video:
                video_item = MediaVideo(video=video, owner=self.owner)
                video_item.save()
                media_frame.video_item = video_item
            elif video_code:
                video_item = MediaVideo(video_code=video_code, owner=self.owner)
                video_item.save()
                media_frame.video_item = video_item
            else:
                raise
            media_frame.owner = self.owner
            media_frame.save()
        return media_frame

tingcraft/mediaframes/views.py
from braces.views import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView, TemplateView
from rest_framework import permissions, status
from rest_framework.response import Response
from rest_framework.views import APIView

from .models import MediaFrame
from .forms import MediaFrameCreateForm, VideoFrameCreateForm
from .serializers import MediaFrameRateSerializer
from core.mixins import OwnerContextMixin, OwnerRequiredMixin


class MediaFrameCreateView(LoginRequiredMixin, OwnerContextMixin, OwnerRequiredMixin, CreateView):

    model = MediaFrame
    form_class = MediaFrameCreateForm
    template_name = 'mediaframes/create.html'

    def get_initial(self):
        self.initial['owner'] = self.request.user
        return super(MediaFrameCreateView, self).get_initial()

    def get_login_url(self):
        return reverse('login')

    def get_success_url(self):
        return self.object.album.get_absolute_url()


class VideoFrameCreateView(LoginRequiredMixin, OwnerContextMixin, OwnerRequiredMixin, CreateView):
    model = MediaFrame
    form_class = VideoFrameCreateForm
    template_name = 'mediaframes/video_create.html'

    def get_initial(self):
        self.initial['owner'] = self.request.user
        return super(VideoFrameCreateView, self).get_initial()

    def get_login_url(self):
        return reverse('login')

    def get_success_url(self):
        return self.object.album.get_absolute_url()


class MediaFrameDeleteView(LoginRequiredMixin, OwnerContextMixin, OwnerRequiredMixin, DeleteView):

    model = MediaFrame

    def get_success_url(self):
        return self.object.album.get_absolute_url()


class MediaFrameDetailView(OwnerContextMixin, DetailView):

    model = MediaFrame
    template_name = 'mediaframes/detail.html'


class MediaFrameRateAPIView(APIView):

    permission_classes = (permissions.AllowAny, )

    def post(self, request, pk, format=None):
        obj = get_object_or_404(MediaFrame, pk=pk)
        serializer = MediaFrameRateSerializer(data=request.DATA)
        if serializer.is_valid():
            if obj.rate_count == 0:
                obj.rating = serializer.object['rating']
            else:
                obj.rating = (obj.rating * obj.rate_count + serializer.object['rating']) / (obj.rate_count + 1)
            obj.rate_count += 1
            obj.save()
            return Response(data={'id': obj.pk, 'rating': "{0:.2f}".format(obj.rating)}, status=status.HTTP_200_OK)
        return Response(data=serializer.errors, status=status.HTTP_400_BAD_REQUEST)

tingcraft/templates/mediaframes/create.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load i18n %}

{% block navigation %}
    {% include 'navigation.html' %}
{% endblock %}

{% block content %}
    <form method="post" action="{% url 'mediaframe:create' owner_username %}" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            <tr>
                <td>{{ form.description.label_tag }}</td>
                <td>{{ form.description }}</td>
            </tr>
            <tr>
                <td>{{ form.album.label_tag }}</td>
                <td>{{ form.album }}</td>
            </tr>
            <tr>
                <td>{{ form.image.label_tag }}</td>
                <td>{{ form.image }}</td>
            </tr>
            <tr>
                <td>{{ form.video_code.label_tag }}</td>
                <td>{{ form.video_code }}</td>
            </tr>
        </table>
        <input type="submit" value="Create MediaFrame" />
    </form>
{% endblock %}

tingcraft/templates/mediaframes/detail.html
{% extends 'user_page_base.html' %}
{% load thumbnail %}
{% load i18n %}
{% load users_tags %}
{% load compressed %}
{% load staticfiles %}

{% block content %}
    <div id="mediaframe-detail-container" data-id="{{ mediaframe.id }}" class="shadow-and-radius">
        <div id="mediaframe-detail-img-container">
            {% if mediaframe.content_type == 'I' %}
                {% thumbnail mediaframe.image_item.image FRAME_DETAIL upscale=False as im %}
                    <img src="{{ im.url }}" class="mediaframe-detail-img middle" width="{{ im.width }}" height="{{ im.height }}"/>
                {% endthumbnail %}
            {% else %}
                {% if mediaframe.video_item.video %}
                    <script type="text/javascript" src="{{ STATIC_URL }}plugin/jwplayer/jwplayer.js"></script>
                    <div id="jw-player" class="middle">Loading the player...</div>
                    <script type="text/javascript">
                        jwplayer("jw-player").setup({
                            file: "{{ mediaframe.video_item.video.url }}",
                            image: "{% static 'img/video-default.jpg' %}",
                            width: 822,
                            height: 480
                        });
                    </script>
                    {% comment %}
                    <video width="720" height="480" class="middle" controls="controls">
                        <source src='{{ mediaframe.video_item.video.url }}' type="{{ mediaframe.video_item.video.content_type }}" />
                        {% trans 'Your browser does not support the video tag.' %}'
                    </video>
                    {% endcomment %}
                {% else %}
                    {{ mediaframe.video_item.video_code|safe }}
                {% endif %}
            {% endif %}
        </div>
        {% if mediaframe.description %}
            <p class="gray right"> {{ mediaframe.description }} </p>
        {% endif %}
        <p class="gray small clear-right right"> {{ mediaframe.created }}</p>
        <p class="gray small clear-right right">{% trans 'Rating: ' %}
            <span id="media-rating">{{ mediaframe.rating|floatformat:2 }}</span>&nbsp;&nbsp;
            <span class="media-rate" data-rating="1">1&nbsp;</span>
            <span class="media-rate" data-rating="2">2&nbsp;</span>
            <span class="media-rate" data-rating="3">3&nbsp;</span>
            <span class="media-rate" data-rating="4">4&nbsp;</span>
            <span class="media-rate" data-rating="5">5</span>
            <span id="media-rate-info"></span>
        </p>
        <span class="clear-right"></span>
        {% if user.username == owner_username %}
            <p><form action="{% url 'mediaframe:delete' owner_username mediaframe.pk %}"><input type="submit" class="btn btn-small right btn-custom" value="{% trans 'Delete' %}"></form></p>
        {% endif %}
        {% if mediaframe.content_type == 'I' %}
            <a href="{{ mediaframe.image_item.image.url }}">{% trans 'Download Original Image' %}</a>
        {% endif %}
    </div>
{% endblock %}

{% block js_in_body %}
    {% compressed_js 'mediaframe' %}
{% endblock %}

tingcraft/templates/mediaframes/list.html
{% extends 'user_page_base.html' %}
{% load thumbnail %}
{% load i18n %}
{% load users_tags %}

{% block content %}
    <div id="frame-list-container">
        <div class="frame-list-description shadow-and-radius">
            <div>
                <p class="font-20">{{ album.name }}</p>
            </div>
            <p>{{ album.description|safe }}</p>
            {% if user.is_authenticated and user.username == owner_username %}
                <div>
                    <a href="{% url 'mediaframe:create' owner_username %}">{% trans 'Add Photo' %}</a>
                    <span> / </span>
                    <a href="{% url 'mediaframe:video_create' owner_username %}">{% trans 'Add Video' %}</a>
                </div>
            {% endif %}
        </div>
        <hr>
        <div>
            {% for mediaframe in mediaframes %}
                {% include 'mediaframes/mediaframe.html' %}
            {% endfor %}
        </div>
        <hr>
    </div>
{% endblock %}

tingcraft/templates/mediaframes/mediaframe.html
{% load thumbnail %}
{% load i18n %}
{% load staticfiles %}

<div class="frame-container">
    <a href="{% url 'mediaframe:detail' owner_username mediaframe.pk %}">
        {% if mediaframe.content_type == 'I' %}
            {% thumbnail mediaframe.image_item.image FRAME_LIST_CROPPED crop='center' as im %}
                <img src="{{ im.url }}" class="mediaframe-image" width="{{ im.width }}" height="{{ im.height }}"/>
            {% endthumbnail %}
        {% else %}
            <img src="{% static 'img/video-default.jpg' %}" class="mediaframe-image" width="282" height="188"/>
        {% endif %}
        <div class="frame-description">
            <p class="right"> {{ mediaframe.description }}# </p>
            <span class="gray small clear-right right"> {{ mediaframe.created }}</span>
            <span class="clear-right"></span>
        </div>
    </a>
</div>

tingcraft/templates/mediaframes/mediaframe_confirm_delete.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <form action="" method="post">{% csrf_token %}
        <p>{% trans 'Are you sure you want to delete this media?' %}</p>
        <input type="submit" value="Confirm" />
    </form>
{% endblock %}

tingcraft/templates/mediaframes/video_create.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load i18n %}

{% block navigation %}
    {% include 'navigation.html' %}
{% endblock %}

{% block content %}
    <form method="post" action="{% url 'mediaframe:video_create' owner_username %}" enctype="multipart/form-data">{% csrf_token %}
        {% if form.errors %}
            <p>{{ form.errors }}</p>
        {% endif %}
        <table>
            <tr>
                <td>{{ form.description.label_tag }}</td>
                <td>{{ form.description }}</td>
            </tr>
            <tr>
                <td>{{ form.album.label_tag }}</td>
                <td>{{ form.album }}</td>
            </tr>
            <tr>
                <td>{{ form.video.label_tag }}</td>
                <td>{{ form.video }}</td>
            </tr>
            <tr>
                <td>{{ form.video_code.label_tag }}</td>
                <td>{{ form.video_code }}</td>
            </tr>
        </table>
        <input type="submit" value="Submit" />
    </form>
{% endblock %}