tingcraft/blogs/urls.py
from django.conf.urls import patterns, include, url

from .views import BlogListView, BlogCreateView, BlogDetailView


urlpatterns = patterns('',

    url(r'^$', BlogListView.as_view(), name='list'),
    url(r'^create/$', BlogCreateView.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/', BlogDetailView.as_view(), name='detail'),

)

tingcraft/tingcraft/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

from .views import HomeView, UserHomeView
from blogs.views import BlogDetailView

admin.autodiscover()

urlpatterns = patterns('',

    url(r'^$', HomeView.as_view(), name='home'),

    url(r'^api/', include('core.api', namespace='api')),
    url(r'^rest/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^ckeditor/', include('ckeditor.urls')),

    url(r'^accounts/', include('users.urls')),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^(?P<username>[-_\w]+)/$', UserHomeView.as_view(), name='user_home'),
    url(r'^(?P<username>[-_\w]+)/microblog/', include('microblogs.urls', namespace='microblog')),
    url(r'^(?P<username>[-_\w]+)/blog/', include('blogs.urls', namespace='blog')),
    url(r'^(?P<username>[-_\w]+)/noteboard/', include('noteboards.urls', namespace='noteboard')),
    url(r'^(?P<username>[-_\w]+)/album/', include('albums.urls', namespace='album')),
    url(r'^(?P<username>[-_\w]+)/mediaframe/', include('mediaframes.urls', namespace='mediaframe')),
    url(r'^(?P<username>[-_\w]+)/experience/', include('experience.urls', namespace='exp')),

)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^assets/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }),
    )

"""
reserved_word is used to validate username to avoid conflict with existing url patterns
"""
import re

url_splitor = re.compile(r'/|\$|\^|\\b')


def get_reserved_words(url_list):
    reserved_words = []
    for item in url_list:
        url_components = url_splitor.split(item.regex.pattern)
        if len(url_components) > 1:
            reserved_words.append(url_components[1])
    reserved_words = list(set(reserved_words))
    print reserved_words
    return reserved_words

reserved_words = get_reserved_words(urlpatterns)

tingcraft/templates/base.html
{% load staticfiles %}
{% load compressed %}
{% load i18n %}

<!DOCTYPE html>
<html class="no-js">
    <head>
        <title>
            {% block page_title %}
                Yiting Li 2013
            {% endblock page_title %}
        </title>

        {% block stylesheets %}
            {% compressed_css 'libs' %}
            {% compressed_css 'ckeditor_custom' %}
            {% compressed_css 'global' %}
        {% endblock stylesheets %}

        {% block head_special %}
        {% endblock %}

        {% block js_in_head %}
            {% compressed_js 'libs' %}
        {% endblock %}

        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
            ga('create', 'UA-44456318-1', 'liyiting.net');
            ga('send', 'pageview');
        </script>
    </head>

    <body>

        {% block background %}
            <div id="general-background"></div>
        {% endblock %}

        {% block body %}
            <div class="navbar navbar-inverse navbar-custom-top">
                {% block navigation %}
                {% endblock %}
            </div>
            <div id='body-container'>
                {% block body_container %}
                    <div id="content">
                        {% block content %}
                        {% endblock %}
                    </div>
                {% endblock %}
            </div>
            <div id="bottom-bar" class="navbar navbar-inverse navbar-custom-bottom text-center">
                <span id="bottom-text">{% trans 'Designed & Coded by Yiting Li, yl2919@columbia.edu' %}</span>
            </div>
            {% block js_in_body %}
            {% endblock %}
        {% endblock %}
    </body>

</html>

tingcraft/templates/index.html
{% extends 'base.html' %}
{% load i18n %}

{% block head_special %}
    <meta property="wb:webmaster" content="8d26f1baa72bf11f" />
{% endblock %}

{% block background %}
    <div id="img-background" style="background-image:url('{{ background_image_url }}');"></div>
{% endblock %}

{% block body %}
    <div id="index-container">
        <a href="{% url 'user_home' 'yiting' %}">
            <h1>{% trans 'Welcome to my Website' %}</h1>
            <h3>{% trans 'Click to Enter' %}</h3>
        </a>
    </div>
{% endblock %}

tingcraft/templates/navigation.html
{% load i18n %}

<ul class="nav navbar-nav navbar-collapse">
    <li><a href="{% url 'user_home' owner_username %}">{% trans 'Home' %}</a></li>
    <li><a href="{% url 'microblog:list' owner_username %}">{% trans 'MicroBlog' %}</a></li>
    <li><a href="{% url 'blog:list' owner_username %}">{% trans 'Blog' %}</a></li>
    <li><a href="{% url 'album:list' owner_username %}">{% trans 'Album' %}</a></li>
    <li><a href="{% url 'noteboard:list' owner_username %}">{% trans 'NoteBoard' %}</a></li>
    <li><a href="{% url 'exp:list' owner_username %}">{% trans 'Experience' %}</a></li>
    {# <li><a href="">{% trans 'FavorFolder' %}</a></li> #}
</ul>
<ul class="nav navbar-nav pull-right">
    {% if user.is_authenticated %}
        <li><form action="{% url 'user_update' %}"><input type="submit" class="btn btn-default navbar-btn right btn-custom" value="{% trans 'Settings' %}"></form></li>
        <li><form action="{% url 'logout' %}"><input type="submit" class="btn btn-default navbar-btn right btn-custom" value="{% trans 'Logout' %}"></form></li>
    {% else %}
        <li><form action="{% url 'login' %}"><input type="submit" class="btn btn-default navbar-btn right btn-custom" value="{% trans 'Login' %}"></form></li>
        <li><form action="{% url 'register' %}"><input type="submit" class="btn btn-default navbar-btn right btn-custom" value="{% trans 'Register' %}"></form></li>
    {% endif %}
</ul>

tingcraft/templates/user_page_base.html
{% extends 'base.html' %}
{% load i18n %}

{% block navigation %}
    {% include 'navigation.html' %}
{% endblock %}

{% block body_container %}
    <div id="header-container">
        <div id="header-profile" data-id="{{ owner.id }}">
            {% block profile_summary %}
                {% include 'users/profile_summary.html' %}
            {% endblock %}
        </div>
    </div>
    <div id="content-container" class="white">
        {% block content %}
            <div id="content-main" class="left">
                {% block content_main %}
                {% endblock %}
            </div>
            <div id="content-sidebar" class="right">
                {% block content_sidebar %}
                    <p align="center">{% trans 'Side Bar' %}</p>
                {% endblock %}
            </div>
            <br class="clear-both"/>
        {% endblock %}
    </div>
{% endblock %}