tingcraft/albums/urls.py
from django.conf.urls import patterns, include, url

from .views import AlbumListView, AlbumCreateView, AlbumMediaFramesView


urlpatterns = patterns('',

    url(r'^$', AlbumListView.as_view(), name='list'),
    url(r'^create/$', AlbumCreateView.as_view(), name='create'),
    url(r'^(?P<slug>[-_\w]+)/$', AlbumMediaFramesView.as_view(), name='mediaframes'),

)

tingcraft/blogs/urls.py
from django.conf.urls import patterns, include, url

from .views import BlogListView, BlogCreateView, BlogDetailView


urlpatterns = patterns('',

    url(r'^$', BlogListView.as_view(), name='list'),
    url(r'^create/$', BlogCreateView.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/', BlogDetailView.as_view(), name='detail'),

)

tingcraft/microblogs/urls.py
from django.conf.urls import patterns, include, url

from .views import MicroBlogListView, MicroBlogCreateView


urlpatterns = patterns('',

    url(r'^$', MicroBlogListView.as_view(), name='list'),
    url(r'^create/$', MicroBlogCreateView.as_view(), name='create'),

)

tingcraft/tingcraft/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

from .views import HomeView, UserHomeView
from blogs.views import BlogDetailView

admin.autodiscover()

urlpatterns = patterns('',

    url(r'^$', HomeView.as_view(), name='home'),

    url(r'^api/', include('core.api', namespace='api')),
    url(r'^rest/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^ckeditor/', include('ckeditor.urls')),

    url(r'^accounts/', include('users.urls')),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^(?P<username>[-_\w]+)/$', UserHomeView.as_view(), name='user_home'),
    url(r'^(?P<username>[-_\w]+)/microblog/', include('microblogs.urls', namespace='microblog')),
    url(r'^(?P<username>[-_\w]+)/blog/', include('blogs.urls', namespace='blog')),
    url(r'^(?P<username>[-_\w]+)/noteboard/', include('noteboards.urls', namespace='noteboard')),
    url(r'^(?P<username>[-_\w]+)/album/', include('albums.urls', namespace='album')),
    url(r'^(?P<username>[-_\w]+)/mediaframe/', include('mediaframes.urls', namespace='mediaframe')),
    url(r'^(?P<username>[-_\w]+)/experience/', include('experience.urls', namespace='exp')),

)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^assets/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }),
    )

"""
reserved_word is used to validate username to avoid conflict with existing url patterns
"""
import re

url_splitor = re.compile(r'/|\$|\^|\\b')


def get_reserved_words(url_list):
    reserved_words = []
    for item in url_list:
        url_components = url_splitor.split(item.regex.pattern)
        if len(url_components) > 1:
            reserved_words.append(url_components[1])
    reserved_words = list(set(reserved_words))
    print reserved_words
    return reserved_words

reserved_words = get_reserved_words(urlpatterns)

tingcraft/microblogs/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings
from model_utils.models import TimeStampedModel


class MicroBlog(TimeStampedModel):

    owner = models.ForeignKey('users.TingUser')
    content = models.CharField(max_length=180, default='', blank=True)
    media_frame = models.ForeignKey('mediaframes.MediaFrame', null=True, blank=True)

    def __unicode__(self):
        return self.content

    def get_absolute_url(self):
        return reverse('microblog:list', kwargs={'username': self.owner.username})

    def get_microcomments(self, max_id, size=settings.PAGE_SIZE['MICROCOMMENT']):
        if max_id == 0:
            return MicroComment.objects.filter(micro_blog=self)[:size]
        else:
            return MicroComment.objects.filter(pk__lt=max_id , micro_blog=self)[:size]


class MicroComment(TimeStampedModel):

    owner = models.ForeignKey('users.TingUser')
    micro_blog = models.ForeignKey('microblogs.MicroBlog')
    content = models.CharField(max_length=180)
    parent_comment = models.ForeignKey('self', null=True, blank=True, on_delete=models.SET_NULL)

tingcraft/microblogs/forms.py
from django import forms

from .models import MicroBlog
from albums.models import Album
from mediaframes.models import MediaFrame
from mediabox.models import MediaImage, MediaVideo


class MicroBlogCreateForm(forms.ModelForm):

    content = forms.CharField(widget=forms.Textarea)
    image = forms.ImageField(required=False)
    video_code = forms.CharField(max_length=255, required=False)
    album = forms.ModelChoiceField(queryset=None, empty_label=None)

    class Meta:
        model = MicroBlog
        fields = ('content', 'image', 'video_code')

    def __init__(self, *args, **kwargs):
        self.owner = kwargs['initial']['owner']
        super(MicroBlogCreateForm, self).__init__(*args, **kwargs)
        self.album = Album.objects.filter(owner=self.owner).order_by('created')
        self.fields['album'].queryset = self.album
        if len(self.album) > 0:
            self.fields['album'].initial = self.album[0]

    def save(self, commit=True):
        microblog = super(MicroBlogCreateForm, self).save(commit=False)
        if commit:
            image = self.cleaned_data['image']
            video_code = self.cleaned_data['video_code']
            album = self.cleaned_data['album']
            if image:
                image_item = MediaImage(image=image, owner=self.owner)
                image_item.save()
                media_frame = MediaFrame(album=album, content_type='I', owner=self.owner)
                media_frame.image_item = image_item
                media_frame.description = self.cleaned_data['content']
                media_frame.save()
                microblog.media_frame = media_frame
            elif video_code:
                video_item = MediaVideo(video_code=video_code, owner=self.owner)
                video_item.save()
                media_frame = MediaFrame(album=album, content_type='V', owner=self.owner)
                media_frame.video_item = video_item
                media_frame.description = self.cleaned_data['content']
                media_frame.save()
                microblog.media_frame = media_frame
            microblog.owner = self.owner
            microblog.save()
        return microblog

tingcraft/microblogs/views.py
from braces.views import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView, TemplateView
from rest_framework.views import APIView
from rest_framework import permissions, status
from rest_framework.response import Response

from .models import MicroBlog
from .forms import MicroBlogCreateForm
from .serializers import MicroBlogSerializer
from users.models import TingUser
from core.pagination import MicroBlogPaginationMixin, MicroBlogPaginationAPIMixin
from core.mixins import OwnerContextMixin


class MicroBlogListView(MicroBlogPaginationMixin, OwnerContextMixin, ListView):

    model = MicroBlog
    context_object_name = 'microblogs'
    template_name = 'microblogs/list.html'

    def dispatch(self, request, *args, **kwargs):
        if request.is_ajax():
            self.template_name = 'microblogs/list_ajax.html'
        return super(MicroBlogListView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = self.owner.get_microblogs(max_id=self.max_id)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(MicroBlogListView, self).get_context_data(**kwargs)
        return context


class MicroBlogListAPIView(MicroBlogPaginationAPIMixin, APIView):

     permission_classes = (permissions.IsAuthenticatedOrReadOnly, )

     def get(self, request, pk, format=None):
        self.owner = get_object_or_404(TingUser, pk=pk)
        self.get_max_id(request)
        queryset = self.owner.get_microblogs(max_id=self.max_id)
        serializer = MicroBlogSerializer(queryset, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)


class MicroBlogCreateView(LoginRequiredMixin, OwnerContextMixin, CreateView):

    model = MicroBlog
    form_class = MicroBlogCreateForm
    template_name = 'microblogs/create.html'

    def get_initial(self):
        self.initial['owner'] = self.request.user
        return super(MicroBlogCreateView, self).get_initial()

    def get_login_url(self):
        return reverse('login')

    def get_sucessful_url(self):
        return reverse('microblog:list', kwargs={'username': self.request.user})

tingcraft/templates/microblogs/create.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load i18n %}

{% block content %}
    <form method="post" action="{% url 'microblog:create' owner_username %}" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            <tr>
                <td>{{ form.content.label_tag }}</td>
                <td>{{ form.content }}</td>
            </tr>
            <tr>
                <td>{{ form.album.label_tag }}</td>
                <td>{{ form.album }}</td>
            </tr>
            <tr>
                <td>{{ form.image.label_tag }}</td>
                <td>{{ form.image }}</td>
            </tr>
            <tr>
                <td>{{ form.video_code.label_tag }}</td>
                <td>{{ form.video_code }}</td>
            </tr>
        </table>
        <input type="submit" value="Create MicroBlog" />
    </form>
{% endblock %}

tingcraft/templates/microblogs/list.html
{% extends 'user_page_base.html' %}
{% load thumbnail %}
{% load i18n %}
{% load users_tags %}
{% load compressed %}

{% block content_main %}
    {% if user.is_authenticated and user.username == owner_username %}
        <div>
            <a href="{% url 'microblog:create' owner_username %}">{% trans 'Create MicroBlog' %}</a>
        </div>
    {% endif %}
    <div id="microblog-list-container">
        {% for microblog in microblogs %}
            {% include 'microblogs/microblog.html' %}
        {% endfor %}
    </div>
    <div>
        <button id="load-more-btn" type="button" class="btn btn-primary btn-block">{% trans 'Load More...' %}</button>
    </div>
{% endblock %}

{% block js_in_body %}
    {% compressed_js 'microblog' %}
{% endblock %}

tingcraft/templates/microblogs/list_ajax.html
{% load thumbnail %}
{% load i18n %}
{% load users_tags %}
{% load compressed %}

{% for microblog in microblogs %}
    {% include 'microblogs/microblog.html' %}
{% endfor %}

tingcraft/templates/microblogs/microblog.html
{% load thumbnail %}
{% load i18n %}

<div class="microblog-container shadow-and-radius" data-id="{{ microblog.id }}">
    <p class="microblog-content">{{ microblog.content }}</p>
    {% if microblog.media_frame and microblog.media_frame.content_type == 'I' %}
        <div class="microblog-image-container">
            <a href="{% url 'mediaframe:detail' owner_username microblog.media_frame.id %}">
            {% thumbnail microblog.media_frame.image_item.image MICROBLOG_IMAGE as im %}
                <img src="{{ im.url }}" class="microblog-image" width="{{ im.width }}" height="{{ im.height }}" />
            {% endthumbnail %}
            </a>
        </div>
        <p class="gray small right"> {% trans 'collected to' %} <a href="{% url 'album:mediaframes' owner_username microblog.media_frame.album.slug %}">{{ microblog.media_frame.album }}</a></p>
    {% endif %}
    <p class="gray small clear-right right">{{ microblog.created }}</p>
    <span class="clear-right"></span>
</div>